// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

const countTransactionsByAccount = `-- name: CountTransactionsByAccount :one
SELECT count(*) FROM transactions
WHERE (account_id = $1 OR counter_account_id = $1)
  AND deleted_at IS NULL
`

// Dùng trước khi xoá ví: ví còn giao dịch thì cảnh báo người dùng.
func (q *Queries) CountTransactionsByAccount(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one

INSERT INTO accounts (id, user_id, name, type, currency, balance, icon)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, type, currency, balance, icon, deleted_at, created_at, updated_at
`

type CreateAccountParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Name     string
	Type     string
	Currency string
	Balance  decimal.Decimal
	Icon     string
}

// Mọi truy vấn ở đây đều có điều kiện user_id.
//
// Đây là điểm bảo mật quan trọng nhất của tầng dữ liệu: nếu chỉ lọc theo
// id, người dùng A chỉ cần đoán được id ví của người dùng B là đọc hoặc
// sửa được ví đó. Ràng buộc user_id ngay trong câu SQL khiến không handler
// nào có thể quên kiểm tra quyền sở hữu.
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Balance,
		arg.Icon,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Balance,
		&i.Icon,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, name, type, currency, balance, icon, deleted_at, created_at, updated_at FROM accounts
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type GetAccountParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Balance,
		&i.Icon,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, user_id, name, type, currency, balance, icon, deleted_at, created_at, updated_at FROM accounts
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
FOR UPDATE
`

type GetAccountForUpdateParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Khoá dòng ví lại trước khi đổi số dư.
//
// FOR UPDATE khiến transaction khác muốn khoá cùng dòng phải xếp hàng
// chờ. Nếu không có nó, hai giao dịch đồng thời trên cùng một ví có thể
// cùng đọc số dư cũ rồi cùng ghi đè, làm mất một trong hai khoản tiền.
func (q *Queries) GetAccountForUpdate(ctx context.Context, arg GetAccountForUpdateParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Balance,
		&i.Icon,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, user_id, name, type, currency, balance, icon, deleted_at, created_at, updated_at FROM accounts
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListAccounts(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Balance,
			&i.Icon,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAccount = `-- name: SoftDeleteAccount :one
UPDATE accounts
SET deleted_at = now()
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, name, type, currency, balance, icon, deleted_at, created_at, updated_at
`

type SoftDeleteAccountParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Xoá mềm để các giao dịch cũ vẫn tham chiếu được tới ví này.
func (q *Queries) SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, softDeleteAccount, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Balance,
		&i.Icon,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $1,
    type = $2,
    icon = $3
WHERE id = $4
  AND user_id = $5
  AND deleted_at IS NULL
RETURNING id, user_id, name, type, currency, balance, icon, deleted_at, created_at, updated_at
`

type UpdateAccountParams struct {
	Name   string
	Type   string
	Icon   string
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.Name,
		arg.Type,
		arg.Icon,
		arg.ID,
		arg.UserID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Balance,
		&i.Icon,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts
SET balance = $1
WHERE id = $2
`

type UpdateAccountBalanceParams struct {
	Balance decimal.Decimal
	ID      uuid.UUID
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.Balance, arg.ID)
	return err
}
