// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
)

const countTransactionsByCategory = `-- name: CountTransactionsByCategory :one
SELECT count(*) FROM transactions
WHERE category_id = $1
  AND deleted_at IS NULL
`

// Dùng trước khi xoá: danh mục còn giao dịch thì không cho xoá, vì xoá đi
// sẽ làm các báo cáo cũ mất một phần dữ liệu.
func (q *Queries) CountTransactionsByCategory(ctx context.Context, categoryID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, user_id, name, type, icon, color)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, type, icon, color, deleted_at, created_at, updated_at
`

type CreateCategoryParams struct {
	ID     uuid.UUID
	UserID *uuid.UUID
	Name   string
	Type   string
	Icon   string
	Color  string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Icon,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, user_id, name, type, icon, color, deleted_at, created_at, updated_at FROM categories
WHERE id = $1
  AND (user_id = $2 OR user_id IS NULL)
  AND deleted_at IS NULL
`

type GetCategoryParams struct {
	ID     uuid.UUID
	UserID *uuid.UUID
}

// Đọc được cả danh mục hệ thống lẫn danh mục của chính mình.
func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many

SELECT id, user_id, name, type, icon, color, deleted_at, created_at, updated_at FROM categories
WHERE (user_id = $1 OR user_id IS NULL)
  AND deleted_at IS NULL
  -- Bỏ trống tham số type thì lấy cả thu lẫn chi.
  AND ($2::text IS NULL OR type = $2)
ORDER BY user_id NULLS FIRST, name
`

type ListCategoriesParams struct {
	UserID *uuid.UUID
	Type   *string
}

// Danh mục có hai loại sống chung trong một bảng:
//
//	user_id IS NULL  → danh mục hệ thống, mọi người dùng đều thấy
//	user_id có giá trị → danh mục riêng của người đó
//
// Quy tắc: ai cũng ĐỌC được danh mục hệ thống, nhưng chỉ SỬA/XOÁ được
// danh mục của chính mình. Quy tắc đó được cài đặt bằng điều kiện WHERE
// chứ không phải bằng if trong Go: câu UPDATE và DELETE dùng
// `user_id = @user_id`, mà danh mục hệ thống có user_id NULL nên không
// bao giờ khớp — tự động được bảo vệ.
// Danh mục hệ thống hiện trước, sau đó xếp theo tên.
func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.UserID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Icon,
			&i.Color,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCategory = `-- name: SoftDeleteCategory :one
UPDATE categories
SET deleted_at = now()
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, name, type, icon, color, deleted_at, created_at, updated_at
`

type SoftDeleteCategoryParams struct {
	ID     uuid.UUID
	UserID *uuid.UUID
}

func (q *Queries) SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, softDeleteCategory, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name  = $1,
    icon  = $2,
    color = $3
WHERE id = $4
  AND user_id = $5
  AND deleted_at IS NULL
RETURNING id, user_id, name, type, icon, color, deleted_at, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name   string
	Icon   string
	Color  string
	ID     uuid.UUID
	UserID *uuid.UUID
}

// Chỉ sửa được danh mục của chính mình: danh mục hệ thống có user_id
// NULL nên điều kiện dưới đây không bao giờ khớp.
func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.ID,
		arg.UserID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
