// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
)

type Querier interface {
	// Dùng trước khi xoá: nguồn tiền còn giao dịch thì không cho xoá.
	CountTransactionsByAccount(ctx context.Context, accountID *uuid.UUID) (int64, error)
	// Mọi truy vấn ở đây đều có điều kiện user_id.
	//
	// Đây là điểm bảo mật quan trọng nhất của tầng dữ liệu: nếu chỉ lọc theo
	// id, người dùng A chỉ cần đoán được id ví của người dùng B là đọc hoặc
	// sửa được ví đó. Ràng buộc user_id ngay trong câu SQL khiến không handler
	// nào có thể quên kiểm tra quyền sở hữu.
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	EmailExists(ctx context.Context, email string) (bool, error)
	GetAccount(ctx context.Context, arg GetAccountParams) (Account, error)
	// Cột email là citext nên so sánh ở đây tự động không phân biệt hoa
	// thường, không cần lower() ở hai vế.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListAccounts(ctx context.Context, userID uuid.UUID) ([]Account, error)
	MarkEmailVerified(ctx context.Context, id uuid.UUID) error
	// Xoá mềm để các giao dịch cũ vẫn tham chiếu được tới ví này.
	SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) (Account, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
