// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
)

type Querier interface {
	// Tổng số giao dịch khớp bộ lọc, để frontend hiện "có N kết quả".
	CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error)
	// Dùng trước khi xoá: nguồn tiền còn giao dịch thì không cho xoá.
	CountTransactionsByAccount(ctx context.Context, accountID *uuid.UUID) (int64, error)
	// Dùng trước khi xoá: danh mục còn giao dịch thì không cho xoá, vì xoá đi
	// sẽ làm các báo cáo cũ mất một phần dữ liệu.
	CountTransactionsByCategory(ctx context.Context, categoryID *uuid.UUID) (int64, error)
	// Mọi truy vấn ở đây đều có điều kiện user_id.
	//
	// Đây là điểm bảo mật quan trọng nhất của tầng dữ liệu: nếu chỉ lọc theo
	// id, người dùng A chỉ cần đoán được id ví của người dùng B là đọc hoặc
	// sửa được ví đó. Ràng buộc user_id ngay trong câu SQL khiến không handler
	// nào có thể quên kiểm tra quyền sở hữu.
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	EmailExists(ctx context.Context, email string) (bool, error)
	GetAccount(ctx context.Context, arg GetAccountParams) (Account, error)
	// Đọc được cả danh mục hệ thống lẫn danh mục của chính mình.
	GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error)
	GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error)
	// Cột email là citext nên so sánh ở đây tự động không phân biệt hoa
	// thường, không cần lower() ở hai vế.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListAccounts(ctx context.Context, userID uuid.UUID) ([]Account, error)
	// Danh mục có hai loại sống chung trong một bảng:
	//   user_id IS NULL  → danh mục hệ thống, mọi người dùng đều thấy
	//   user_id có giá trị → danh mục riêng của người đó
	//
	// Quy tắc: ai cũng ĐỌC được danh mục hệ thống, nhưng chỉ SỬA/XOÁ được
	// danh mục của chính mình. Quy tắc đó được cài đặt bằng điều kiện WHERE
	// chứ không phải bằng if trong Go: câu UPDATE và DELETE dùng
	// `user_id = @user_id`, mà danh mục hệ thống có user_id NULL nên không
	// bao giờ khớp — tự động được bảo vệ.
	// Danh mục hệ thống hiện trước, sau đó xếp theo tên.
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	//
	// Phân trang bằng CON TRỎ chứ không dùng OFFSET.
	//
	// OFFSET có hai vấn đề: database vẫn phải đọc và bỏ đi toàn bộ số dòng
	// được bỏ qua nên trang càng sau càng chậm; và nếu có giao dịch mới được
	// thêm giữa hai lần gọi thì các trang sau bị lệch, người dùng thấy lặp
	// hoặc mất bản ghi.
	//
	// Con trỏ ở đây là cặp (occurred_at, id). Cần cả hai vì nhiều giao dịch
	// có thể trùng ngày; id là chốt chặn để thứ tự luôn xác định. Phép so
	// sánh bộ (a, b) < (c, d) của Postgres so sánh theo thứ tự từ trái sang,
	// đúng như thứ tự sắp xếp.
	//
	// Các tham số lọc dùng sqlc.narg: để NULL nghĩa là không lọc theo tiêu
	// chí đó.
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	MarkEmailVerified(ctx context.Context, id uuid.UUID) error
	// Tổng tiền theo từng danh mục trong một kỳ.
	//
	// LEFT JOIN chứ không phải INNER JOIN: giao dịch ghi nhanh không có danh
	// mục vẫn phải xuất hiện trong báo cáo, gom vào nhóm "Chưa phân loại".
	// Dùng INNER JOIN sẽ âm thầm bỏ sót chúng và tổng của báo cáo sẽ nhỏ hơn
	// tổng chi thực tế.
	ReportByCategory(ctx context.Context, arg ReportByCategoryParams) ([]ReportByCategoryRow, error)
	// Thu và chi gom theo từng tháng.
	//
	// Phải đổi về múi giờ địa phương TRƯỚC khi cắt theo tháng. occurred_at
	// lưu theo UTC, nên một khoản chi lúc 06:00 ngày 01/08 giờ Việt Nam
	// tương ứng 23:00 ngày 31/07 UTC — nếu gom theo UTC nó sẽ rơi nhầm vào
	// tháng 7.
	//
	// Chỉ trả về tháng CÓ giao dịch; tháng trống được điền ở tầng service để
	// biểu đồ không bị đứt quãng.
	ReportCashFlow(ctx context.Context, arg ReportCashFlowParams) ([]ReportCashFlowRow, error)
	// Toàn bộ báo cáo tổng hợp theo cột occurred_at (thời điểm tiền thực sự
	// thu/chi), KHÔNG theo created_at. Hôm nay nhập bữa ăn của hôm qua thì
	// khoản đó phải nằm trong báo cáo của hôm qua.
	//
	// Khoảng thời gian luôn là nửa mở [from, to): lấy >= from và < to. Nhờ
	// vậy hai kỳ liền nhau không bao giờ đếm trùng một giao dịch nằm đúng
	// ranh giới.
	// Tổng thu, tổng chi và số giao dịch trong một kỳ.
	//
	// FILTER (WHERE ...) là cách Postgres gộp nhiều phép tính có điều kiện
	// khác nhau vào MỘT lần quét bảng. Nếu tách thành hai câu SUM riêng thì
	// phải quét bảng hai lần cho cùng một khoảng dữ liệu.
	//
	// COALESCE để kỳ không có giao dịch nào trả về 0 thay vì NULL.
	ReportSummary(ctx context.Context, arg ReportSummaryParams) (ReportSummaryRow, error)
	// Xoá mềm để các giao dịch cũ vẫn tham chiếu được tới ví này.
	SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) (Account, error)
	SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) (Category, error)
	SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (Transaction, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	// Chỉ sửa được danh mục của chính mình: danh mục hệ thống có user_id
	// NULL nên điều kiện dưới đây không bao giờ khớp.
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
