// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlc

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

const reportByCategory = `-- name: ReportByCategory :many
SELECT
    t.category_id                       AS category_id,
    COALESCE(c.name,  '')               AS category_name,
    COALESCE(c.icon,  '')               AS category_icon,
    COALESCE(c.color, '')               AS category_color,
    SUM(t.amount)::NUMERIC(19,4)        AS total_amount,
    COUNT(*)                            AS transaction_count
FROM transactions t
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1
  AND t.deleted_at IS NULL
  AND t.type = $2
  AND t.occurred_at >= $3
  AND t.occurred_at <  $4
GROUP BY t.category_id, c.name, c.icon, c.color
ORDER BY total_amount DESC
`

type ReportByCategoryParams struct {
	UserID   uuid.UUID
	Type     string
	FromTime time.Time
	ToTime   time.Time
}

type ReportByCategoryRow struct {
	CategoryID       *uuid.UUID
	CategoryName     string
	CategoryIcon     string
	CategoryColor    string
	TotalAmount      decimal.Decimal
	TransactionCount int64
}

// Tổng tiền theo từng danh mục trong một kỳ.
//
// LEFT JOIN chứ không phải INNER JOIN: giao dịch ghi nhanh không có danh
// mục vẫn phải xuất hiện trong báo cáo, gom vào nhóm "Chưa phân loại".
// Dùng INNER JOIN sẽ âm thầm bỏ sót chúng và tổng của báo cáo sẽ nhỏ hơn
// tổng chi thực tế.
func (q *Queries) ReportByCategory(ctx context.Context, arg ReportByCategoryParams) ([]ReportByCategoryRow, error) {
	rows, err := q.db.Query(ctx, reportByCategory,
		arg.UserID,
		arg.Type,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportByCategoryRow{}
	for rows.Next() {
		var i ReportByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
			&i.TotalAmount,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportCashFlow = `-- name: ReportCashFlow :many
SELECT
    date_trunc('month', t.occurred_at AT TIME ZONE $1::text)::TIMESTAMP AS period,
    COALESCE(SUM(t.amount) FILTER (WHERE t.type = 'income'),  0)::NUMERIC(19,4) AS total_income,
    COALESCE(SUM(t.amount) FILTER (WHERE t.type = 'expense'), 0)::NUMERIC(19,4) AS total_expense
FROM transactions t
WHERE t.user_id = $2
  AND t.deleted_at IS NULL
  AND t.occurred_at >= $3
  AND t.occurred_at <  $4
GROUP BY period
ORDER BY period
`

type ReportCashFlowParams struct {
	Timezone string
	UserID   uuid.UUID
	FromTime time.Time
	ToTime   time.Time
}

type ReportCashFlowRow struct {
	Period       time.Time
	TotalIncome  decimal.Decimal
	TotalExpense decimal.Decimal
}

// Thu và chi gom theo từng tháng.
//
// Phải đổi về múi giờ địa phương TRƯỚC khi cắt theo tháng. occurred_at
// lưu theo UTC, nên một khoản chi lúc 06:00 ngày 01/08 giờ Việt Nam
// tương ứng 23:00 ngày 31/07 UTC — nếu gom theo UTC nó sẽ rơi nhầm vào
// tháng 7.
//
// Chỉ trả về tháng CÓ giao dịch; tháng trống được điền ở tầng service để
// biểu đồ không bị đứt quãng.
func (q *Queries) ReportCashFlow(ctx context.Context, arg ReportCashFlowParams) ([]ReportCashFlowRow, error) {
	rows, err := q.db.Query(ctx, reportCashFlow,
		arg.Timezone,
		arg.UserID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportCashFlowRow{}
	for rows.Next() {
		var i ReportCashFlowRow
		if err := rows.Scan(&i.Period, &i.TotalIncome, &i.TotalExpense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSummary = `-- name: ReportSummary :one

SELECT
    COALESCE(SUM(amount) FILTER (WHERE type = 'income'),  0)::NUMERIC(19,4) AS total_income,
    COALESCE(SUM(amount) FILTER (WHERE type = 'expense'), 0)::NUMERIC(19,4) AS total_expense,
    COUNT(*) AS transaction_count
FROM transactions
WHERE user_id = $1
  AND deleted_at IS NULL
  AND occurred_at >= $2
  AND occurred_at <  $3
`

type ReportSummaryParams struct {
	UserID   uuid.UUID
	FromTime time.Time
	ToTime   time.Time
}

type ReportSummaryRow struct {
	TotalIncome      decimal.Decimal
	TotalExpense     decimal.Decimal
	TransactionCount int64
}

// Toàn bộ báo cáo tổng hợp theo cột occurred_at (thời điểm tiền thực sự
// thu/chi), KHÔNG theo created_at. Hôm nay nhập bữa ăn của hôm qua thì
// khoản đó phải nằm trong báo cáo của hôm qua.
//
// Khoảng thời gian luôn là nửa mở [from, to): lấy >= from và < to. Nhờ
// vậy hai kỳ liền nhau không bao giờ đếm trùng một giao dịch nằm đúng
// ranh giới.
// Tổng thu, tổng chi và số giao dịch trong một kỳ.
//
// FILTER (WHERE ...) là cách Postgres gộp nhiều phép tính có điều kiện
// khác nhau vào MỘT lần quét bảng. Nếu tách thành hai câu SUM riêng thì
// phải quét bảng hai lần cho cùng một khoảng dữ liệu.
//
// COALESCE để kỳ không có giao dịch nào trả về 0 thay vì NULL.
func (q *Queries) ReportSummary(ctx context.Context, arg ReportSummaryParams) (ReportSummaryRow, error) {
	row := q.db.QueryRow(ctx, reportSummary, arg.UserID, arg.FromTime, arg.ToTime)
	var i ReportSummaryRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense, &i.TransactionCount)
	return i, err
}
