// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

const countTransactions = `-- name: CountTransactions :one
SELECT count(*) FROM transactions
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::text        IS NULL OR type        = $2)
  AND ($3::uuid IS NULL OR category_id = $3)
  AND ($4::uuid  IS NULL OR account_id  = $4)
  AND ($5::timestamptz IS NULL OR occurred_at >= $5)
  AND ($6::timestamptz   IS NULL OR occurred_at <  $6)
`

type CountTransactionsParams struct {
	UserID     uuid.UUID
	Type       *string
	CategoryID *uuid.UUID
	AccountID  *uuid.UUID
	From       *time.Time
	To         *time.Time
}

// Tổng số giao dịch khớp bộ lọc, để frontend hiện "có N kết quả".
func (q *Queries) CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions,
		arg.UserID,
		arg.Type,
		arg.CategoryID,
		arg.AccountID,
		arg.From,
		arg.To,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    id, user_id, account_id, category_id, type, amount, currency, note, occurred_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, user_id, account_id, category_id, type, amount, currency, note, occurred_at, deleted_at, created_at, updated_at
`

type CreateTransactionParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	AccountID  *uuid.UUID
	CategoryID *uuid.UUID
	Type       string
	Amount     decimal.Decimal
	Currency   string
	Note       string
	OccurredAt time.Time
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.Currency,
		arg.Note,
		arg.OccurredAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Note,
		&i.OccurredAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, account_id, category_id, type, amount, currency, note, occurred_at, deleted_at, created_at, updated_at FROM transactions
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type GetTransactionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Note,
		&i.OccurredAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, user_id, account_id, category_id, type, amount, currency, note, occurred_at, deleted_at, created_at, updated_at FROM transactions
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::text        IS NULL OR type        = $2)
  AND ($3::uuid IS NULL OR category_id = $3)
  AND ($4::uuid  IS NULL OR account_id  = $4)
  AND ($5::timestamptz IS NULL OR occurred_at >= $5)
  AND ($6::timestamptz   IS NULL OR occurred_at <  $6)
  AND (
        $7::timestamptz IS NULL
        OR (occurred_at, id) < ($7, $8::uuid)
      )
ORDER BY occurred_at DESC, id DESC
LIMIT $9
`

type ListTransactionsParams struct {
	UserID           uuid.UUID
	Type             *string
	CategoryID       *uuid.UUID
	AccountID        *uuid.UUID
	From             *time.Time
	To               *time.Time
	CursorOccurredAt *time.Time
	CursorID         *uuid.UUID
	PageSize         int32
}

// Phân trang bằng CON TRỎ chứ không dùng OFFSET.
//
// OFFSET có hai vấn đề: database vẫn phải đọc và bỏ đi toàn bộ số dòng
// được bỏ qua nên trang càng sau càng chậm; và nếu có giao dịch mới được
// thêm giữa hai lần gọi thì các trang sau bị lệch, người dùng thấy lặp
// hoặc mất bản ghi.
//
// Con trỏ ở đây là cặp (occurred_at, id). Cần cả hai vì nhiều giao dịch
// có thể trùng ngày; id là chốt chặn để thứ tự luôn xác định. Phép so
// sánh bộ (a, b) < (c, d) của Postgres so sánh theo thứ tự từ trái sang,
// đúng như thứ tự sắp xếp.
//
// Các tham số lọc dùng sqlc.narg: để NULL nghĩa là không lọc theo tiêu
// chí đó.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.UserID,
		arg.Type,
		arg.CategoryID,
		arg.AccountID,
		arg.From,
		arg.To,
		arg.CursorOccurredAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.Note,
			&i.OccurredAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :one
UPDATE transactions
SET deleted_at = now()
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, account_id, category_id, type, amount, currency, note, occurred_at, deleted_at, created_at, updated_at
`

type SoftDeleteTransactionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, softDeleteTransaction, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Note,
		&i.OccurredAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET account_id  = $1,
    category_id = $2,
    type        = $3,
    amount      = $4,
    note        = $5,
    occurred_at = $6
WHERE id = $7
  AND user_id = $8
  AND deleted_at IS NULL
RETURNING id, user_id, account_id, category_id, type, amount, currency, note, occurred_at, deleted_at, created_at, updated_at
`

type UpdateTransactionParams struct {
	AccountID  *uuid.UUID
	CategoryID *uuid.UUID
	Type       string
	Amount     decimal.Decimal
	Note       string
	OccurredAt time.Time
	ID         uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.AccountID,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.Note,
		arg.OccurredAt,
		arg.ID,
		arg.UserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Note,
		&i.OccurredAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
